"""
Security policy system for ClioraOps.

Controls file access, resource usage, and security boundaries.
"""

import os
import yaml
from pathlib import Path
from typing import List, Dict, Optional
from enum import Enum


class PolicyLevel(Enum):
    """Security policy levels."""
    PERMISSIVE = "permissive"
    MODERATE = "moderate"
    STRICT = "strict"
    SANDBOX = "sandbox"


class AccessPolicy:
    """
    File and directory access control policy.

    Defines what files and directories can be accessed, modified,
    or generated by ClioraOps.
    """

    def __init__(self, policy_dict: Optional[Dict] = None):
        """Initialize policy from a dictionary or use defaults."""
        self.policy = policy_dict or self._default_policy()
        self.level = PolicyLevel(self.policy.get("level", "moderate"))

    @staticmethod
    def _default_policy() -> Dict:
        """Get default security policy."""
        return {
            "level": "moderate",
            "allowed_paths": [
                str(Path.home() / ".clioraops"),
                str(Path.cwd()),
                "/tmp",
                "/var/tmp",
            ],
            "blocked_paths": [
                "/etc",
                "/root",
                "/sys",
                "/proc",
                "/boot",
            ],
            "allowed_file_types": [
                ".py", ".yaml", ".yml", ".json", ".txt", ".md",
                ".sh", ".dockerfile",
                ".tf", ".tfvars", ".xml", ".toml",
            ],
            "blocked_file_types": [
                ".exe", ".bin", ".so",
            ],
            "max_file_size_mb": 100,
            "max_generated_files": 1000,
            "file_creation_allowed": True,
            "file_modification_allowed": True,
            "file_deletion_allowed": False,
            "symlink_creation_allowed": False,
            "external_command_execution_allowed": False,
        }

    @staticmethod
    def load_from_file(filepath: Path) -> "AccessPolicy":
        """Load policy from a YAML file."""
        try:
            if filepath.exists():
                with open(filepath, "r", encoding="utf-8") as file:
                    policy_dict = yaml.safe_load(file) or {}
                return AccessPolicy(policy_dict)
        except (OSError, yaml.YAMLError, ValueError, TypeError):
            pass

        return AccessPolicy()

    def is_path_allowed(self, path: str) -> bool:
        """
        Check whether a path is inside an allowed directory and outside
        every blocked directory.

        Resolved Path objects provide proper directory-boundary checks
        across Windows and POSIX systems.
        """
        try:
            target_path = Path(path).expanduser().resolve()

            # Blocked paths always take precedence.
            for blocked in self.policy.get("blocked_paths", []):
                blocked_path = Path(blocked).expanduser().resolve()

                try:
                    target_path.relative_to(blocked_path)
                    return False
                except ValueError:
                    continue

            allowed_paths = self.policy.get("allowed_paths", [])

            if not allowed_paths:
                return True

            for allowed in allowed_paths:
                allowed_path = Path(allowed).expanduser().resolve()

                try:
                    target_path.relative_to(allowed_path)
                    return True
                except ValueError:
                    continue

            return False

        except (OSError, RuntimeError, ValueError, TypeError):
            # Fail closed if the path cannot be resolved safely.
            return False

    def is_file_type_allowed(self, filename: str) -> bool:
        """Check whether a file extension is allowed."""
        _, ext = os.path.splitext(filename)
        ext = ext.lower()

        blocked = {
            item.lower()
            for item in self.policy.get("blocked_file_types", [])
        }
        if ext in blocked:
            return False

        allowed = {
            item.lower()
            for item in self.policy.get("allowed_file_types", [])
        }
        if allowed and ext not in allowed:
            return False

        return True

    def is_file_size_allowed(self, size_bytes: int) -> bool:
        """Check whether a file size is within configured limits."""
        if size_bytes < 0:
            return False

        max_mb = self.policy.get("max_file_size_mb", 100)
        max_bytes = max_mb * 1024 * 1024
        return size_bytes <= max_bytes

    def can_create_files(self) -> bool:
        """Check whether file creation is allowed."""
        return self.policy.get("file_creation_allowed", True)

    def can_modify_files(self) -> bool:
        """Check whether file modification is allowed."""
        return self.policy.get("file_modification_allowed", True)

    def can_delete_files(self) -> bool:
        """Check whether file deletion is allowed."""
        return self.policy.get("file_deletion_allowed", False)

    def can_create_symlinks(self) -> bool:
        """Check whether symbolic-link creation is allowed."""
        return self.policy.get("symlink_creation_allowed", False)

    def is_operation_allowed(
        self,
        operation: str,
        path: str = None,
        size: int = None,
    ) -> bool:
        """Check whether an operation is permitted."""
        operation = operation.strip().lower()

        if operation not in {"create", "modify", "delete", "symlink", "execute"}:
            return False

        if path is not None:
            if not self.is_path_allowed(path):
                return False

            if operation in {"create", "modify", "delete"}:
                target = Path(path).expanduser()

                # Existing directories are not files, so do not
                # apply file-extension restrictions to them.
                is_directory = target.is_dir()

                # A nonexistent output directory is valid for a
                # create operation when its parent is allowed.
                if (
                    operation == "create"
                    and not target.exists()
                    and not target.suffix
                ):
                    is_directory = True

                if not is_directory and not self.is_file_type_allowed(path):
                    return False

        if size is not None and not self.is_file_size_allowed(size):
            return False

        if operation == "create":
            return self.can_create_files()

        if operation == "modify":
            return self.can_modify_files()

        if operation == "delete":
            return self.can_delete_files()

        if operation == "symlink":
            return self.can_create_symlinks()

        if operation == "execute":
            return self.policy.get(
                "external_command_execution_allowed", False
            )

        return False
    
    def get_policy_summary(self) -> str:
        """Return a human-readable policy summary."""
        lines = [
            f"Security Level: {self.level.value.upper()}",
            f"File Creation: {'Allowed' if self.can_create_files() else 'Blocked'}",
            f"File Modification: {'Allowed' if self.can_modify_files() else 'Blocked'}",
            f"File Deletion: {'Allowed' if self.can_delete_files() else 'Blocked'}",
            f"Symlink Creation: {'Allowed' if self.can_create_symlinks() else 'Blocked'}",
            "External Command Execution: "
            + (
                "Allowed"
                if self.policy.get("external_command_execution_allowed", False)
                else "Blocked"
            ),
            f"Max File Size: {self.policy.get('max_file_size_mb', 100)} MB",
        ]

        allowed_paths = self.policy.get("allowed_paths", [])
        if allowed_paths:
            lines.append(f"Allowed Paths: {', '.join(allowed_paths[:3])}")

        blocked_paths = self.policy.get("blocked_paths", [])
        if blocked_paths:
            lines.append(f"Blocked Paths: {', '.join(blocked_paths[:3])}")

        return "\n".join(lines)


def load_policy() -> AccessPolicy:
    """
    Load policy from user configuration, project configuration,
    or defaults, in that priority order.
    """
    user_policy = Path.home() / ".clioraops" / "policy.yaml"
    if user_policy.exists():
        return AccessPolicy.load_from_file(user_policy)

    project_policy = Path.cwd() / ".clioraops-policy.yaml"
    if project_policy.exists():
        return AccessPolicy.load_from_file(project_policy)

    return AccessPolicy()


def create_default_policy_file() -> None:
    """Create a default policy file in the user configuration directory."""
    config_dir = Path.home() / ".clioraops"
    policy_file = config_dir / "policy.yaml"

    config_dir.mkdir(parents=True, exist_ok=True)

    if policy_file.exists():
        return

    default_policy = AccessPolicy()

    with open(policy_file, "w", encoding="utf-8") as file:
        yaml.safe_dump(
            default_policy.policy,
            file,
            default_flow_style=False,
        )
